repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: eoapi
    url: https://devseed.com/eoapi-k8s/
  - name: community-charts
    url: https://community-charts.github.io/helm-charts
  - name: zenml-ecr
    url: public.ecr.aws/zenml
    oci: true

helmDefaults:
  wait: true
  createNamespace: true

releases:
  - name: cert-manager
    namespace: cert-manager
    chart: jetstack/cert-manager
    version: "v1.20.1"
    labels:
      tier: ingress
    timeout: 300
    set:
      - name: crds.enabled
        value: true

  - name: ingress-nginx
    namespace: ingress-nginx
    chart: ingress-nginx/ingress-nginx
    version: "4.15.1"
    labels:
      tier: ingress
    timeout: 300
    values:
      - ingress/values.yaml

  - name: stac
    namespace: fair
    chart: eoapi/eoapi
    version: "0.12.2"
    labels:
      tier: app
    wait: true
    timeout: 600
    needs:
      - ingress-nginx/ingress-nginx
    values:
      - stac/values.yaml.gotmpl

  - name: mlflow
    namespace: fair
    chart: community-charts/mlflow
    version: "1.8.1"
    labels:
      tier: app
    timeout: 300
    needs:
      - ingress-nginx/ingress-nginx
    values:
      - mlflow/values.yaml.gotmpl

  - name: zenml
    namespace: fair
    chart: zenml-ecr/zenml
    version: 0.93.3
    labels:
      tier: app
    timeout: 480
    needs:
      - ingress-nginx/ingress-nginx
    values:
      - zenml/values.yaml.gotmpl
