apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stac
  namespace: fair
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
    - secretName: stac-tls
      hosts:
        - "{{STAC_HOST}}"
  rules:
    - host: "{{STAC_HOST}}"
      http:
        paths:
          - path: /(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: stac-stac
                port:
                  number: 8080
          - path: /stac(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: stac-stac
                port:
                  number: 8080
