stack_name: dev
zenml_version: 0.93.3
components:
  orchestrator:
    name: default
    flavor: local
    type: orchestrator
    configuration: {}
  artifact_store:
    name: s3_local
    flavor: s3
    type: artifact_store
    configuration:
      path: s3://zenml
      client_kwargs:
        endpoint_url: "http://localhost:9000"
        aws_access_key_id: minioadmin
        aws_secret_access_key: minioadmin
  experiment_tracker:
    name: mlflow_local
    flavor: mlflow
    type: experiment_tracker
    configuration:
      tracking_uri: "http://localhost:5000"
      tracking_username: admin
      tracking_password: admin
