stack_name: local
zenml_version: 0.93.2
components:
  orchestrator:
    name: local_orchestrator
    flavor: local
    type: orchestrator
    configuration: {}
  artifact_store:
    name: local_artifacts
    flavor: local
    type: artifact_store
    configuration:
      path: artifacts
  # experiment_tracker:
  #   name: mlflow_tracker
  #   flavor: mlflow
  #   type: experiment_tracker
  #   configuration:
  #     tracking_uri: "${MLFLOW_TRACKING_URI}"
