apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: predict
type: Opaque
stringData:
  AWS_ENDPOINT_URL: "http://minio.fair.svc:9000"
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
