"""Shared FairClient integration test for all model pipelines.

Runs inside Docker CI after build. Uses local ZenML server, STAC catalog,
and toy data generated by each model's conftest.
Validates the full workflow: setup -> register -> finetune -> promote -> predict.

Pass --model-dir=models/<name> to select which model to test.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path
from typing import Any

import pytest


@pytest.fixture(scope="module")
def work_dir(tmp_path_factory: pytest.TempPathFactory) -> Path:
    return tmp_path_factory.mktemp("integration")


@pytest.fixture(scope="module")
def generate_toy_dataset(model_dir: Path, tmp_path_factory: pytest.TempPathFactory) -> dict[str, Any]:
    import importlib.util

    conftest_path = model_dir / "tests" / "conftest.py"
    spec = importlib.util.spec_from_file_location("model_conftest", conftest_path)
    assert spec is not None and spec.loader is not None
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.create_toy_data(tmp_path_factory.mktemp(f"toy_{model_dir.name}"))


@pytest.fixture(scope="module")
def dataset_stac_item(generate_toy_dataset: dict[str, Any]) -> Path:
    return generate_toy_dataset["dataset_stac_item"]


@pytest.fixture(scope="module")
def predict_images(generate_toy_dataset: dict[str, Any]) -> str:
    return str(generate_toy_dataset["chips"])


@pytest.fixture(scope="module")
def zenml_server(work_dir: Path):
    zenml_bin = Path(sys.executable).parent / "zenml"
    env = {**os.environ, "ZENML_CONFIG_PATH": str(work_dir / ".zen")}
    subprocess.run([str(zenml_bin), "init"], check=True, capture_output=True, cwd=str(work_dir), env=env)
    proc = subprocess.Popen(
        [str(zenml_bin), "login", "--local"],
        cwd=str(work_dir),
        env=env,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )
    import time

    time.sleep(5)
    yield env
    proc.terminate()
    proc.wait(timeout=10)


@pytest.fixture(scope="module")
def fair_client(work_dir: Path, zenml_server: dict[str, str]) -> Any:
    from fair.client import FairClient

    catalog_path = str(work_dir / "stac_catalog" / "catalog.json")
    config_dir = str(work_dir / "config")
    return FairClient(
        catalog_path=catalog_path,
        user_id="test",
        config_dir=config_dir,
    )


@pytest.mark.slow
def test_full_pipeline(
    fair_client: Any,
    model_dir: Path,
    dataset_stac_item: Path,
    predict_images: str,
    zenml_server: dict[str, str],
) -> None:
    os.environ.update(zenml_server)

    fair_client.setup()

    base_model_id = fair_client.register_base_model(str(model_dir / "stac-item.json"))
    assert base_model_id

    dataset_id = fair_client.register_dataset(str(dataset_stac_item))
    assert dataset_id

    model_name = f"test-{model_dir.name}"
    finetuned_id = fair_client.finetune(
        base_model_id=base_model_id,
        dataset_id=dataset_id,
        model_name=model_name,
        overrides={"epochs": 1, "batch_size": 2},
    )
    assert finetuned_id

    local_model_id = fair_client.promote(finetuned_id, description="integration test")
    assert local_model_id

    predictions = fair_client.predict(local_model_id, image_path=predict_images)
    assert predictions["type"] == "FeatureCollection"
    assert "features" in predictions
